
        spring:
            profiles:cloud-config
            application:
              name: Logistic-Cloud-Server
         eureka:
             client:
                  register-with-eureka: true
                  fatch-registry: true
                  service-url:
                          defaultZone: http://localhost:8761/eureka/
            instance:
                  hostname:localhost

                  
spring profile= cloud-config
spring application name = Spring-Microservice-Ecommerce-Cloud-Server
eureka client register-with-eureka = true
eureka client fatch-registry = true
eureka client service-url= defaultZone: http://localhost:8761/eureka/
eureka instance hostname = localhost                  
