server:
  port: 9191
spring:
  application:
    name: CONFIG-SERVER
  cloud:
    config:
      enable: true
      server:
        git:
          uri:  https://github.com/obagaji/config-server1
          skipSslValidation: true
          timeout: 4
          deleteUntrackedBranches: true

